import {
  AWS,
  Django,
  Docker,
  Elastic,
  Electron,
  ExpressJsLight,
  FastAPI,
  Git,
  HTML5,
  Java,
  JavaScript,
  JQuery,
  Kibana,
  MongoDB,
  MySQL,
  NodeJs,
  Postman,
  Python,
  React,
  ReactRouter,
  Redis,
  Solidity,
  TypeScript,
} from "developer-icons";

export const SKILLS_DETAILS = [
  {
    skillCategory: "Languages",
    toolIcons: [
      { Icon: Python, name: "Python" },
      { Icon: Java, name: "Java" },
      { Icon: Solidity, name: "Solidity" },
      { Icon: JavaScript, name: "JavaScript" },
      { Icon: HTML5, name: "HTML5" },
    ],
  },
  {
    skillCategory: "Backend",
    toolIcons: [
      { Icon: Django, name: "Django" },
      { Icon: FastAPI, name: "FastAPI" },
      { Icon: NodeJs, name: "Node.js" },
      { Icon: ExpressJsLight, name: "Express.js" },
    ],
  },
  {
    skillCategory: "Frontend",
    toolIcons: [
      { Icon: React, name: "React" },
      { Icon: Electron, name: "Electron" },
      { Icon: TypeScript, name: "TypeScript" },
      { Icon: JQuery, name: "jQuery" },
    ],
  },
  {
    skillCategory: "Other Tech",
    toolIcons: [
      { Icon: MySQL, name: "MySQL" },
      { Icon: MongoDB, name: "MongoDB" },
      { Icon: Redis, name: "Redis" },
      { Icon: AWS, name: "AWS" },
      { Icon: Git, name: "Git" },
      { Icon: Elastic, name: "Elasticsearch" },
      { Icon: Docker, name: "Docker" },
      { Icon: Postman, name: "Postman" },
      { Icon: Kibana, name: "Kibana" },
    ],
  },
];
